---
title: "Table"
output: papaja::apa6_pdf
note: "2023-02-09"
---

```{r}


library(papaja)
# Source = rep("Source", 7)
# I_con = rep("Icon", 7)
# gams = rep("\U03B3", 7)
# ls = rep("l", 7)

# gams[c(2,3)] = c(m.g_pog, m.g_ml)
# I_con = c("No", "No", "No", "No", 1, 1, "TBD")
# ls[c(2,3)] =  ceiling(c(l.pog, l.ml))



contrast = c("N", "Y", "N", "Y", "N", "Y", "N", "N", "N")
gams_sample = rep("g", 9)
gams_model = rep("g", 9)
r.7 = rep("n1", 9)
r.9 = rep("n2", 9)
tab = cbind(contrast, gams_sample, gams_model, r.7, r.9)

rownames(tab)=c("1. Weight",
                "2. Contrast",
                "3. Overall",
                "4. Contrast",
                "5. Overall",
                "6. Contrast",
                "7. Overall",
                "8. Mueller-Lyar",
                "9. Poggendorf")
colnames(tab)=c(
            "Contrast",
            "Sample",
            "Model",
            "0.7",
            "0.9")

names(dimnames(tab)) = "Task"
apa_table(tab,
          escape = F,
          col_spanners = list('Design' = 2,
                              'Signal-To-Noise SD Estimates' = c(3, 4), 
                              'Recommended Trial Size' = c(5,6)),
          stub_indents = list('Army ' = c(1,1),
                              "Stroop" = c(2,3), 
                              "Flanker" = c(4,5),
                              "Lexical Distance " = c(6,7),
                              "Illusions" = c(8,9)),
          note="SD for Weight...",
          format.args = list(margin=1),digits=c(0,0,0,2,0,0,0,0),
          align = c("l",rep("c",5)))



```

```{r}
makeTab = F

if (makeTab){
  source('newModLib.R')
  source('aux.R')
  
  gammas_sample = 1:9
  gammas_model = 1:9
  l.r9 = 1:9
  l.r7 = 1:9
  
  ## We need the army gamma model_based estimates
  gammas_model[1] = NA
  datArmy = makeArmyDat()
  gammas_sample[1] = sqrt(var(datArmy)/9 - 1/1)
  
  stroop <- readRMStroopI()
  flank <- readRMFlankI()
  task=rep(1:2,c(length(stroop$sub),length(flank$sub)))
  dat <-rbind(stroop,flank)
  dat$task <-task
  ssub <- unique(stroop$sub)
  fsub <- unique(flank$sub)
  goodSub <- intersect(ssub,fsub)
  datRM <- dat[dat$sub %in% goodSub,]
  outFlank=est5(datRM[datRM$task==2,],M=3000,burn=200,tuneT=.16, tuneA = 1)
  outStroop=est5(datRM[datRM$task==1,],M=3000,burn=200,tuneT=.16, tuneA = 1)
  
  
  gammas_model[2] = mean(1/sqrt(outStroop$pGammaTheta))
  gammas_model[3] = mean(1/sqrt(outStroop$pGammaAlpha))
  gammas_model[4] = mean(1/sqrt(outFlank$pGammaTheta))
  gammas_model[5] = mean(1/sqrt(outFlank$pGammaAlpha))
  
  sampOutFlannk = sampEstG(datRM[datRM$task==2,], contrast = T)
  sampOutStroop = sampEstG(datRM[datRM$task==1,], contrast = T)  
  gammas_sample[2] = sampOutStroop$g_bar_theta
  gammas_sample[3] = sampOutStroop$g_bar_alpha
  gammas_sample[4] = sampOutFlannk$g_bar_theta
  gammas_sample[5] = sampOutFlannk$g_bar_alpha
  
  
  
  datIll <- readIllusion()
  datIll$task = as.integer(as.factor(datIll$task)) 
  datIll$y= ifelse(datIll$task==1,-datIll$bias*100,datIll$bias)
  outML=est3(datIll[datIll$task==1,],M=3000,burn=200,tune=1)
  outPog=est3(datIll[datIll$task==2,],M=3000,burn=200,tune=1)
  
  gammas_model[6] = mean(1/sqrt(outML$pGamma))
  gammas_model[7] = mean(1/sqrt(outPog$pGamma))
  
  sampOutMl = sampEstG(datIll[datIll$task==1,])
  sampOutPog = sampEstG(datIll[datIll$task==2,])  
  
  gammas_sample[6] = sampOutMl
  gammas_sample[7] = sampOutPog
  
  datFive = readRouderOtherI()
  outFive=est5(datFive,M=3000,burn=200,tuneT=.16, tuneA = 1)
  
  gammas_model[8] = mean(1/sqrt(outFive$pGammaTheta))
  gammas_model[9] = mean(1/sqrt(outFive$pGammaAlpha))
  
  
  sampOutFive = sampEstG(datFive, contrast = T)
  gammas_sample[8] = sampOutFive$g_bar_theta
  gammas_sample[9] = sampOutFive$g_bar_alpha
  
  l.r7[1] = lSizeForR(r=.7, g2=gammas_sample[1]^2)
  l.r9[1] = lSizeForR(r=.9, g2=gammas_sample[1]^2)
  l.r7[c(2:5,8,9)] = lSizeForR(r=.7, g2=gammas_model[c(2:5,8,9)]^2, cond = T)
  l.r9[c(2:5,8,9)] = lSizeForR(r=.9, g2=gammas_model[c(2:5,8,9)]^2, cond = T)
  l.r7[6:7] = lSizeForR(r=.7, g2=gammas_model[6:7]^2)
  l.r9[6:7] = lSizeForR(r=.9, g2=gammas_model[6:7]^2)
  
  tab = cbind(contrast, 
              round(gammas_sample,2), 
              round(gammas_model,2), 
              ceiling(l.r7), 
              ceiling(l.r9))
  saveRDS(tab, "table.RDS")
}

if(!makeTab){
  tab = readRDS("table.RDS")
}

  
rownames(tab)=c("1. Weight",
                "2. Contrast",
                "3. Overall",
                "4. Contrast",
                "5. Overall",
                "6. Contrast",
                "7. Overall",
                "8. Mueller-Lyar",
                "9. Poggendorf")
colnames(tab)=c(
            "Contrast",
            "Sample",
            "Model",
            "0.7",
            "0.9")

names(dimnames(tab)) = "Task"
apa_table(tab,
          escape = F,
          col_spanners = list('Design' = 2,
                              'Signal-To-Noise SD Estimates' = c(3, 4), 
                              'Recommended Trial Size' = c(5,6)),
          stub_indents = list('Army ' = c(1,1),
                              "Stroop" = c(2,3), 
                              "Flanker" = c(4,5),
                              "Lexical Distance " = c(6,7),
                              "Illusions" = c(8,9)),
          note="SD for Weight...",
          format.args = list(margin=1),digits=c(0,0,0,2,0,0,0,0),
          align = c("l",rep("c",5)))
```